# Site settings
title: CS3216 Software Development on Evolving Platforms
email: cs3216-staff@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official homepage for CS3216: Software Development on Evolving Platforms.
  Subscribe to updates using the RSS button!
url: http://cs3216.github.io # the base hostname & protocol for your site
facebook_username: cs3216
github_username: cs3216
github_repo: cs3216.github.io

# Build settings
markdown: kramdown
permalink: /:title
paginate: 5
encoding: UTF-8
gems: ['jekyll-paginate']
